<?php
o2def::model("_o2alpha", "A", "C50", "");
o2def::model("_o2date", "D", "-", "");
o2def::model("_o2logical", "L", "", "");
o2def::model("_o2number", "N", "8", "");
o2def::model("_o2sid", "A", "C32", "");
o2def::model("_o2structure", "S", "", "");
o2def::model("_o2text", "A", "C10000000", "");
o2def::model("_o2time", "O", ":", "");
o2def::model("applink_type", "A", "U1[ |Control|Form|Program]", "");
o2def::model("ctrl_name", "A", "C100", "");
o2def::model("form_name", "A", "C200", "");
o2def::model("key_word", "A", "U30", "");
o2def::model("node_desc", "A", "U200", "");
o2def::model("node_href", "A", "C200", "");
o2def::model("node_id", "N", "8", "");
o2def::model("node_text", "A", "C100000000", "");
o2def::model("node_title", "A", "C200", "");
o2def::model("program_name", "A", "C200", "");
o2def::model("setting_key", "A", "L20", "");
o2def::model("title_level", "N", "1Z", "");
o2def::model("use_desc", "A", "U1L49", "");
o2def::model("use_id", "N", "3", "");
?>
