#! /bin/bash


JXPATH=""     # Path to Janox runtime
JXPHPEXE=""   # Path to PHP executable
JXAPPSCR=""   # Path to Janox application main file

echo

# ___________________________________________ LOOK FOR JANOX RUNTIME ___
if [[ -f "$JXRNT" ]] # _______ Try to use JXRNT environment variable ___
then
   JXPATH="$JXRNT"
else # ______________________________________ Try to use script path ___
   SCRORI=`readlink $0`
   if [[ -n $SCRORI ]] # If script is a symlink (ex. /usr/bin/janox) ___
   then
      JXPATH=$(dirname $SCRORI)
   else
      JXPATH=$(dirname $0)
   fi
   if [[ -f "$JXPATH/jxrnt.php" ]] # __________ Check runtime script ___
   then
      JXPATH="$JXPATH/jxrnt.php"
   else # __________________ Error message for missing Janox runtime ___
       echo
       echo -e "\e[31;1m*** Cannot find a suitable Janox runtime.\e[0m"
       echo -e "    \e[31;1mJXRNT environment variable is not set.\e[0m"
       echo -e "    \e[31;1mPath $JXPATH does not lead to Janox.\e[0m"
       echo
       exit # __________________________________________________________
   fi
fi

# __________________________________________ LOOK FOR PHP EXECUTABLE ___
JXINI=$(dirname $JXPATH)/janox.ini
if [[ -r "$JXINI" ]]
then
   # ________________________________ Try to use option in janox.ini ___
   JXPHPEXE=`grep "php_exe\s*=\s*.*$" /janox/jxrnt/janox.ini | cut -d= -f2`
   JXPHPEXE=${JXPHPEXE//\"/}
   JXPHPEXE=`which $JXPHPEXE`
   if [[ ! -x $JXPHPEXE ]]
   then
      JXPHPEXE=""
   fi
fi

if [[ -z $JXPHPEXE ]]
then
   # _____________________________________________________ Try "php" ___
   JXPHPEXE=`which php`
   if [[ ! -x $JXPHPEXE ]]
   then
      JXPHPEXE=""
   fi
fi

if [[ -z $JXPHPEXE ]] # ____ Error message for missing Janox runtime ___
then
   echo
   echo -e "\e[31;1m*** Cannot find a suitable PHP executable.\e[0m"
   echo -e "    \e[31;1mphp_exe option in janox.ini is not set.\e[0m"
   echo -e "    \e[31;1m\"php\" command seems not callable.\e[0m"
   echo
   exit # ______________________________________________________________
fi

echo -e '\e[33mStarting Janox...\e[0m'
echo

# ______________________________________ LOOK FOR APPLICATION TO RUN ___
if [[ -n $1 ]] # __________________ If application script was passed ___
then
   if [[ -f $1 ]] # _ If file name leads to an application main file ___
   then
      JXAPPSCR=$1
   elif [[ -n $JXAPP && -r "$JXAPP/$1/htdocs/$1.php" ]]
   then
      JXAPPSCR="${JXAPP%/}/$1/htdocs/$1.php"
   else # ______________________ Error message for wrong application ___
       echo -e "\e[31;1m*** Cannot find Janox application\e[0m"
       echo -e "    \e[31;1m$1\e[0m"
       echo
       exit # __________________________________________________________
   fi
   # _________________ Test if requested file is a Janox application ___
   if [[ -z `grep "o2def::app\s*[(]" $JXAPPSCR` ]]
   then
       echo -e "\e[31;1m*** $JXAPPSCR is not a Janox application.\e[0m"
       echo
      exit # ___________________________________________________________
   fi
   echo -e " * PHP executable: \e[33m$JXPHPEXE\e[0m"
   echo -e " * Janox runtime:  \e[33m$JXPATH\e[0m"
   echo -e " * Application:    \e[33m$JXAPPSCR\e[0m"
   if  [[ -n $2 ]]
   then
      echo -e " -                 \e[33m$2\e[0m"
      if  [[ -n $3 ]]
      then
         echo -e " -                 \e[33m$3\e[0m"
         if  [[ -n $4 ]]
         then
            echo -e " -                 \e[33m$4\e[0m"
            if  [[ -n $5 ]]
            then
               echo -e " -                 \e[33m$5\e[0m"
            fi
         fi
      fi
   fi
   echo
   "$JXPHPEXE" "$JXAPPSCR" "jxrnt=$JXPATH" $2 $3 $4 $5
else # _ If no application execution then runtime is called for info ___
   "$JXPHPEXE" "$JXPATH"
fi

