<?php

/**
 * Janox Application Module
 * PHP5
 *
 *
 * This file is part of Janox.
 *
 * Janox is free software; you can redistribute it and/or modify it under the
 * terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 3 of the License, or (at your option)
 * any later version.
 *
 * Janox is distributed in the hope that it will be useful, but WITHOUT ANY
 * WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 *
 * You should have received a copy of the GNU Lesser General Public License
 * along with this program. If not, see <http://www.gnu.org/licenses/>.
 *
 *
 * This script contains Win1252 encoded internal strings.
 * NOTE: This script MUST be encoded in Windows-1252 (CP1252).
 *
 *
 * @name      jxapp
 * @package   janox/jxconts.inc
 * @version   2.9
 * @copyright Tommaso Vannini (tvannini@janox.it) 2007
 * @author    Tommaso Vannini (tvannini@janox.it)
 */

// ____________________________________ Constants for internal Win1252 encoded strings ___
define('JX_DEF_DELIMITER', '§§');
define('JX_VIRT_VIEW',     'prg§_§var');

?>